
###
POST http://localhost:5000/api/msg/62a512cf1cc23324971a2e87 HTTP/1.1
Content-Type: application/json

{
    "from":{
        "id":"62a4fabafb74ec19ecabb414",
        "name":"test0"
    },
    "to":{
        "id":"62a4fb22fb74ec19ecabb41a",
        "name":"test1"
    },
    "content":"They are shit"
}
