
###
POST http://localhost:5000/api/msg/62a521d8dd16053eca6d2d1a HTTP/1.1
Content-Type: application/json

{
    "to":{
        "id":"62a520e7dd16053eca6d2d0f",
        "name":"test0"
    },
    "from":
        {
        "id":"62a52100dd16053eca6d2d12",
        "name":"test1"
    },
    
    
    "content":"yes ikr"
}


###
GET http://localhost:5000/api/msg/62a521d8dd16053eca6d2d1a HTTP/1.1
