###
POST http://localhost:5000/api/room HTTP/1.1
Content-Type: application/json

{
    "name":"sample_room",
    "desc":"this is a sample room",
    "admins":[{
        "name":"test1",
        "id":"62a52100dd16053eca6d2d12"}]
    
}

###
PATCH  http://localhost:5000/api/room/62a521d8dd16053eca6d2d1a HTTP/1.1
Content-Type: application/json

{
    "uid":"62a520e7dd16053eca6d2d0f",
    "name":"test0",
    "code":"7ZA32Z"
}

###
GET http://localhost:5000/api/room/code/62a521d8dd16053eca6d2d1a HTTP/1.1
Content-Type: application/json

{
    "uid":"62a52100dd16053eca6d2d12"
}

###
GET http://localhost:5000/api/room/admins/:id HTTP/1.1

###
GET http://localhost:5000/api/room/u/:id HTTP/1.1


###
GET http://localhost:5000/api/room/62a521d8dd16053eca6d2d1a HTTP/1.1


###
GET http://localhost:5000/api/room/62a521d8dd16053eca6d2d1a HTTP/1.1

###


