###

POST http://localhost:5000/api/user HTTP/1.1
content-type: application/json

{
    "email":"testAdmin3@test.com",
    "name":"testA3",
    "isAdmin":false
}


###
POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email":"test@test.com"
}

###
GET http://localhost:5000/api/user/tickets/:id HTTP/1.1

###
GET http://localhost:5000/api/user/rooms/:id HTTP/1.1

###
GET http://localhost:5000/api/user/admin/:id HTTP/1.1


